apiVersion: batch/v1
kind: CronJob
metadata:
  name: model-trainer-job
spec:
  # Ejecuta cada 2 minutos (perfecto para demo)
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: model-trainer
              # TODO: Reemplaza xmane13 con tu username de Docker Hub
              image: xmane13/ml-trainer:1.0.0
              imagePullPolicy: Always
              volumeMounts:
                - name: model-volume
                  mountPath: /shared-volume
          volumes:
            - name: model-volume
              persistentVolumeClaim:
                claimName: model-pvc
